version: '3.8'

services:
  # Next.js Application Service
  nextjs-app:
    image: waseera-web-site
    container_name: nextjs-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - MONGODB_URI_FILE=/run/secrets/mongodb_uri
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    secrets:
      - mongodb_uri
    networks:
      - backend
      - frontend

  # MongoDB Service
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    volumes:
      - mongodb-data:/var/lib/mongodb/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/mongodb_user
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongodb_password
    secrets:
      - mongodb_user
      - mongodb_password
    ports:
      - "27017:27017"
    networks:
      - backend

  # Nginx Service for Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - nextjs-app
    networks:
      - frontend

volumes:
  mongodb-data:
    driver: local
    driver_opts:
      type: none
      device: /var/lib/docker/volumes/mongodb/data
      o: bind

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

secrets:
  mongodb_user:
    file: ./secrets/mongodb_user.txt
  mongodb_password:
    file: ./secrets/mongodb_password.txt
  mongodb_uri:
    file: ./secrets/mongodb_uri.txt
