version: '3.8'

services:
  waseera-web-site:
    image: afettah/waseera-web-site
    container_name: waseera-web-site
    environment:
      - NODE_ENV=production
      - MONGODB_URI_FILE=/run/secrets/waseera-web-site_mongodb_uri
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    secrets:
      - waseera-web-site_mongodb_uri
    networks:
      - backend
      - frontend

  # MongoDB Service
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/mongodb_user
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongodb_password
    secrets:
      - mongodb_user
      - mongodb_password
    ports:
      - "27017:27017"
    networks:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - waseera-web-site
    networks:
      - frontend

volumes:
  mongodb-data:
    driver: local
    driver_opts:
      type: none
      device: /var/lib/waseera-data/mongodb/data
      o: bind

networks:
  frontend:
    driver: overlay
  backend:
    driver: overlay

secrets:
  mongodb_user:
    external: true
  mongodb_password:
    external: true
  waseera-web-site_mongodb_uri:
    external: true