import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import TopBar from "./topBar";
import TopMenu from "./topMenu";
import SubContainer from "./components/sub-container";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col bg-transparent `}
      >
        <SubContainer>
          <TopBar />
          <TopMenu />
        </SubContainer>

        {children}
      </body>
    </html>
  );
}
